-- Migration: 20250108160000_seed_essential_data.sql
-- Description: Seeds essential data for department types and medicines

-- First ensure department types are present
INSERT INTO department_types (name) VALUES 
    ('General Medicine'),
    ('Cardiology'),
    ('Neurology'),
    ('Pediatrics'),
    ('Orthopedics'),
    ('Dermatology'),
    ('Psychiatry'),
    ('Emergency Medicine'),
    ('Ophthalmology'),
    ('ENT'),
    ('Dental'),
    ('Gynecology'),
    ('Urology'),
    ('Pulmonology'),
    ('Endocrinology')
ON CONFLICT (name) DO NOTHING;

-- Create medicines table if not exists (safety check)
CREATE TABLE IF NOT EXISTS medicines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    price numeric(10,2),
    is_discontinued boolean DEFAULT false,
    manufacturer_name text,
    pack_size_label text,
    pack_type text,
    short_composition1 text,
    short_composition2 text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Insert common medicines
INSERT INTO medicines (
    name, 
    price, 
    manufacturer_name, 
    pack_size_label, 
    pack_type, 
    short_composition1, 
    short_composition2
) VALUES 
    ('Paracetamol 500mg Tablet', 5.00, 'Generic Pharma', '10 tablets', 'Strip', 'Paracetamol 500mg', NULL),
    ('Amoxicillin 500mg Capsule', 12.50, 'ABC Pharmaceuticals', '10 capsules', 'Strip', 'Amoxicillin 500mg', NULL),
    ('Omeprazole 20mg Capsule', 15.00, 'Healthcare Ltd', '10 capsules', 'Strip', 'Omeprazole 20mg', NULL),
    ('Metformin 500mg Tablet', 8.00, 'Diabetes Care', '15 tablets', 'Strip', 'Metformin HCl 500mg', NULL),
    ('Amlodipine 5mg Tablet', 10.00, 'Heart Pharma', '10 tablets', 'Strip', 'Amlodipine Besylate 5mg', NULL),
    ('Cetirizine 10mg Tablet', 6.00, 'Allergy Care', '10 tablets', 'Strip', 'Cetirizine HCl 10mg', NULL),
    ('Aspirin 75mg Tablet', 4.50, 'Heart Care', '14 tablets', 'Strip', 'Acetylsalicylic Acid 75mg', NULL),
    ('Diclofenac 50mg Tablet', 7.00, 'Pain Relief Inc', '10 tablets', 'Strip', 'Diclofenac Sodium 50mg', NULL),
    ('Azithromycin 500mg Tablet', 25.00, 'Antibiotics Ltd', '3 tablets', 'Strip', 'Azithromycin 500mg', NULL),
    ('Pantoprazole 40mg Tablet', 18.00, 'Gastro Care', '10 tablets', 'Strip', 'Pantoprazole 40mg', NULL);

-- Insert more medicines
INSERT INTO medicines (
    name, 
    price, 
    manufacturer_name, 
    pack_size_label, 
    pack_type, 
    short_composition1, 
    short_composition2
) VALUES 
    ('Metoprolol 25mg Tablet', 12.00, 'Beta Care', '10 tablets', 'Strip', 'Metoprolol Tartrate 25mg', NULL),
    ('Ciprofloxacin 500mg Tablet', 15.00, 'Antibiotic Plus', '10 tablets', 'Strip', 'Ciprofloxacin 500mg', NULL),
    ('Montelukast 10mg Tablet', 20.00, 'Asthma Care', '10 tablets', 'Strip', 'Montelukast Sodium 10mg', NULL),
    ('Vitamin D3 60000IU Capsule', 40.00, 'Vitamin Care', '4 capsules', 'Strip', 'Cholecalciferol 60000IU', NULL),
    ('Calcium + Vitamin D3 Tablet', 15.00, 'Bone Health', '15 tablets', 'Strip', 'Calcium 500mg', 'Vitamin D3 250IU'),
    ('Cough Syrup', 45.00, 'Respiratory Care', '100ml', 'Bottle', 'Dextromethorphan', 'Chlorpheniramine'),
    ('Ibuprofen 400mg Tablet', 8.00, 'Pain Care', '10 tablets', 'Strip', 'Ibuprofen 400mg', NULL),
    ('Ranitidine 150mg Tablet', 9.00, 'Gastro Plus', '10 tablets', 'Strip', 'Ranitidine 150mg', NULL),
    ('Ambroxol Syrup', 35.00, 'Chest Care', '100ml', 'Bottle', 'Ambroxol HCl', NULL),
    ('Multivitamin Tablet', 25.00, 'Vitamin Plus', '10 tablets', 'Strip', 'Multiple Vitamins', 'Minerals');

-- Insert specialized medicines
INSERT INTO medicines (
    name, 
    price, 
    manufacturer_name, 
    pack_size_label, 
    pack_type, 
    short_composition1, 
    short_composition2
) VALUES 
    ('Eye Drops', 50.00, 'Vision Care', '10ml', 'Bottle', 'Artificial Tears', NULL),
    ('Nasal Spray', 60.00, 'Nasal Care', '20ml', 'Bottle', 'Oxymetazoline', NULL),
    ('Insulin Injection', 500.00, 'Diabetes Plus', '10ml', 'Vial', 'Human Insulin', NULL),
    ('B-Complex Tablet', 15.00, 'Vitamin Care', '10 tablets', 'Strip', 'Vitamin B Complex', NULL),
    ('Antacid Suspension', 40.00, 'Gastro Care', '200ml', 'Bottle', 'Magnesium Hydroxide', 'Aluminium Hydroxide');

-- Enable RLS on medicines table
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;

-- Add policy to allow all authenticated users to read medicines
CREATE POLICY "medicines_read_all" ON medicines
    FOR SELECT TO authenticated
    USING (true);

-- Also allow public read access for unauthenticated users
CREATE POLICY "medicines_read_public" ON medicines
    FOR SELECT TO anon
    USING (true);
