-- Create required enums first
CREATE TYPE "public"."appointment_status" AS ENUM ('Scheduled', 'In Progress', 'Completed', 'Cancelled');
CREATE TYPE "public"."appointment_type" AS ENUM ('Walk-in', 'Digital');
CREATE TYPE "public"."bill_status" AS ENUM ('Paid', 'Pending', 'Overdue');

-- Create appointments table
CREATE TABLE "public"."appointments" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "clinic_id" uuid NOT NULL,
    "patient_id" uuid NOT NULL,
    "doctor_id" uuid NOT NULL,
    "date" text NOT NULL,
    "time" text NOT NULL,
    "type" appointment_type DEFAULT 'Walk-in'::appointment_type,
    "status" appointment_status DEFAULT 'Scheduled'::appointment_status,
    "notes" text,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."appointments" ENABLE ROW LEVEL SECURITY;

-- Create patients table
CREATE TABLE "public"."patients" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "clinic_id" uuid NOT NULL,
    "name" text NOT NULL,
    "email" text,
    "phone" text,
    "gender" text,
    "date_of_birth" date,
    "medical_id" text,
    "address" text,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."patients" ENABLE ROW LEVEL SECURITY;

-- Create consultations table
CREATE TABLE "public"."consultations" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "appointment_id" uuid,
    "clinic_id" uuid NOT NULL,
    "patient_id" uuid NOT NULL,
    "doctor_id" uuid,
    "specialty_data" jsonb,
    "clinical_notes" jsonb,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."consultations" ENABLE ROW LEVEL SECURITY;

-- Create bills table
CREATE TABLE "public"."bills" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "clinic_id" uuid NOT NULL,
    "patient_id" uuid NOT NULL,
    "appointment_id" uuid,
    "amount" numeric NOT NULL,
    "items" jsonb,
    "status" bill_status DEFAULT 'Pending'::bill_status,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "description" text,
    "invoice_number" text NOT NULL,
    "service_items" jsonb,
    "discount_percentage" numeric(5,2) DEFAULT 0,
    "tax_percentage" numeric(5,2) DEFAULT 0,
    "billing_type" text DEFAULT 'simple'::text,
    "notes" text
);

ALTER TABLE "public"."bills" ENABLE ROW LEVEL SECURITY;

-- Create payment_transactions table
CREATE TABLE "public"."payment_transactions" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "clinic_id" uuid NOT NULL,
    "transaction_type" character varying(50) NOT NULL,
    "amount" numeric(10,2) NOT NULL,
    "currency" character varying(3) NOT NULL DEFAULT 'INR'::character varying,
    "credits_purchased" integer,
    "razorpay_payment_id" character varying(255),
    "razorpay_order_id" character varying(255),
    "razorpay_signature" character varying(255),
    "payment_status" character varying(50) NOT NULL DEFAULT 'pending'::character varying,
    "payment_method" character varying(50),
    "metadata" jsonb DEFAULT '{}'::jsonb,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."payment_transactions" ENABLE ROW LEVEL SECURITY;

-- Create medicines table
CREATE TABLE "public"."medicines" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "price" numeric(10,2),
    "is_discontinued" boolean DEFAULT false,
    "manufacturer_name" text,
    "pack_size_label" text,
    "pack_type" text,
    "short_composition1" text,
    "short_composition2" text,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."medicines" ENABLE ROW LEVEL SECURITY;

-- Create prescriptions table
CREATE TABLE "public"."prescriptions" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "clinic_id" uuid NOT NULL,
    "patient_id" uuid NOT NULL,
    "doctor_id" uuid NOT NULL,
    "appointment_id" uuid,
    "consultation_id" uuid,
    "medications" jsonb,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."prescriptions" ENABLE ROW LEVEL SECURITY;

-- Create appointment_billing table
CREATE TABLE "public"."appointment_billing" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "appointment_id" uuid NOT NULL,
    "clinic_id" uuid NOT NULL,
    "billing_type" character varying(50) NOT NULL,
    "amount" numeric(10,2) NOT NULL DEFAULT 10.00,
    "credits_used" integer DEFAULT 1,
    "monthly_billing_cycle_id" uuid,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."appointment_billing" ENABLE ROW LEVEL SECURITY;

-- Create clinic_credits table
CREATE TABLE "public"."clinic_credits" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "clinic_id" uuid NOT NULL,
    "credit_balance" integer NOT NULL DEFAULT 0,
    "total_credits_purchased" integer NOT NULL DEFAULT 0,
    "total_credits_used" integer NOT NULL DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."clinic_credits" ENABLE ROW LEVEL SECURITY;

-- Create monthly_billing_cycles table
CREATE TABLE "public"."monthly_billing_cycles" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "clinic_id" uuid NOT NULL,
    "billing_month" date NOT NULL,
    "appointments_count" integer NOT NULL DEFAULT 0,
    "total_amount" numeric(10,2) NOT NULL DEFAULT 0,
    "payment_status" character varying(50) NOT NULL DEFAULT 'pending'::character varying,
    "payment_transaction_id" uuid,
    "due_date" date NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."monthly_billing_cycles" ENABLE ROW LEVEL SECURITY;

-- Add primary key constraints
ALTER TABLE "public"."appointments" ADD CONSTRAINT "appointments_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."patients" ADD CONSTRAINT "patients_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."consultations" ADD CONSTRAINT "consultations_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."bills" ADD CONSTRAINT "bills_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."payment_transactions" ADD CONSTRAINT "payment_transactions_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."medicines" ADD CONSTRAINT "medicines_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."prescriptions" ADD CONSTRAINT "prescriptions_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."appointment_billing" ADD CONSTRAINT "appointment_billing_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."clinic_credits" ADD CONSTRAINT "clinic_credits_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."monthly_billing_cycles" ADD CONSTRAINT "monthly_billing_cycles_pkey" PRIMARY KEY ("id");

-- Add unique constraints
ALTER TABLE "public"."appointment_billing" ADD CONSTRAINT "appointment_billing_appointment_id_key" UNIQUE ("appointment_id");
ALTER TABLE "public"."clinic_credits" ADD CONSTRAINT "clinic_credits_clinic_id_unique" UNIQUE ("clinic_id");

-- Add foreign key constraints
ALTER TABLE "public"."appointments" ADD CONSTRAINT "appointments_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;
ALTER TABLE "public"."appointments" ADD CONSTRAINT "appointments_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;
ALTER TABLE "public"."appointments" ADD CONSTRAINT "appointments_doctor_id_fkey" FOREIGN KEY ("doctor_id") REFERENCES "public"."doctors"("id");

ALTER TABLE "public"."patients" ADD CONSTRAINT "patients_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;

ALTER TABLE "public"."consultations" ADD CONSTRAINT "consultations_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;
ALTER TABLE "public"."consultations" ADD CONSTRAINT "consultations_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;
ALTER TABLE "public"."consultations" ADD CONSTRAINT "consultations_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "public"."appointments"("id") ON DELETE CASCADE;
ALTER TABLE "public"."consultations" ADD CONSTRAINT "consultations_doctor_id_fkey" FOREIGN KEY ("doctor_id") REFERENCES "public"."doctors"("id");

ALTER TABLE "public"."bills" ADD CONSTRAINT "bills_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;
ALTER TABLE "public"."bills" ADD CONSTRAINT "bills_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;
ALTER TABLE "public"."bills" ADD CONSTRAINT "bills_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "public"."appointments"("id");

ALTER TABLE "public"."payment_transactions" ADD CONSTRAINT "payment_transactions_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;

ALTER TABLE "public"."prescriptions" ADD CONSTRAINT "prescriptions_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;
ALTER TABLE "public"."prescriptions" ADD CONSTRAINT "prescriptions_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE CASCADE;
ALTER TABLE "public"."prescriptions" ADD CONSTRAINT "prescriptions_doctor_id_fkey" FOREIGN KEY ("doctor_id") REFERENCES "public"."doctors"("id");
ALTER TABLE "public"."prescriptions" ADD CONSTRAINT "prescriptions_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "public"."appointments"("id");
ALTER TABLE "public"."prescriptions" ADD CONSTRAINT "prescriptions_consultation_id_fkey" FOREIGN KEY ("consultation_id") REFERENCES "public"."consultations"("id");

ALTER TABLE "public"."appointment_billing" ADD CONSTRAINT "appointment_billing_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;
ALTER TABLE "public"."appointment_billing" ADD CONSTRAINT "appointment_billing_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "public"."appointments"("id") ON DELETE CASCADE;
ALTER TABLE "public"."appointment_billing" ADD CONSTRAINT "appointment_billing_monthly_billing_cycle_id_fkey" FOREIGN KEY ("monthly_billing_cycle_id") REFERENCES "public"."monthly_billing_cycles"("id");

ALTER TABLE "public"."clinic_credits" ADD CONSTRAINT "clinic_credits_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;

ALTER TABLE "public"."monthly_billing_cycles" ADD CONSTRAINT "monthly_billing_cycles_clinic_id_fkey" FOREIGN KEY ("clinic_id") REFERENCES "public"."clinics"("id") ON DELETE CASCADE;
ALTER TABLE "public"."monthly_billing_cycles" ADD CONSTRAINT "monthly_billing_cycles_payment_transaction_id_fkey" FOREIGN KEY ("payment_transaction_id") REFERENCES "public"."payment_transactions"("id");

-- Create RLS policies for HIPAA compliance and multi-tenant isolation

-- Appointments policies
CREATE POLICY "clinic_isolation_appointments" ON "public"."appointments"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Patients policies
CREATE POLICY "clinic_isolation_patients" ON "public"."patients"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Consultations policies
CREATE POLICY "clinic_isolation_consultations" ON "public"."consultations"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Bills policies
CREATE POLICY "clinic_isolation_bills" ON "public"."bills"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Payment transactions policies
CREATE POLICY "clinic_isolation_payment_transactions" ON "public"."payment_transactions"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Medicines policies (global access for medicine database)
CREATE POLICY "medicines_read_access" ON "public"."medicines"
FOR SELECT USING (true);

-- Prescriptions policies
CREATE POLICY "clinic_isolation_prescriptions" ON "public"."prescriptions"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Appointment billing policies
CREATE POLICY "clinic_isolation_appointment_billing" ON "public"."appointment_billing"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Clinic credits policies
CREATE POLICY "clinic_isolation_clinic_credits" ON "public"."clinic_credits"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Monthly billing cycles policies
CREATE POLICY "clinic_isolation_monthly_billing_cycles" ON "public"."monthly_billing_cycles"
FOR ALL USING (
  "clinic_id" IN (
    SELECT cm."clinic_id" FROM "public"."clinic_members" cm 
    WHERE cm."user_id" = auth.uid()
  )
);

-- Create indexes for performance optimization
CREATE INDEX "idx_appointments_clinic_id" ON "public"."appointments" ("clinic_id");
CREATE INDEX "idx_appointments_patient_id" ON "public"."appointments" ("patient_id");
CREATE INDEX "idx_appointments_doctor_id" ON "public"."appointments" ("doctor_id");
CREATE INDEX "idx_appointments_date" ON "public"."appointments" ("date");
CREATE INDEX "idx_appointments_status" ON "public"."appointments" ("status");

CREATE INDEX "idx_patients_clinic_id" ON "public"."patients" ("clinic_id");
CREATE INDEX "idx_patients_medical_id" ON "public"."patients" ("medical_id");
CREATE INDEX "idx_patients_email" ON "public"."patients" ("email");
CREATE INDEX "idx_patients_phone" ON "public"."patients" ("phone");

CREATE INDEX "idx_consultations_clinic_id" ON "public"."consultations" ("clinic_id");
CREATE INDEX "idx_consultations_patient_id" ON "public"."consultations" ("patient_id");
CREATE INDEX "idx_consultations_appointment_id" ON "public"."consultations" ("appointment_id");
CREATE INDEX "idx_consultations_doctor_id" ON "public"."consultations" ("doctor_id");

CREATE INDEX "idx_bills_clinic_id" ON "public"."bills" ("clinic_id");
CREATE INDEX "idx_bills_patient_id" ON "public"."bills" ("patient_id");
CREATE INDEX "idx_bills_appointment_id" ON "public"."bills" ("appointment_id");
CREATE INDEX "idx_bills_status" ON "public"."bills" ("status");
CREATE INDEX "idx_bills_invoice_number" ON "public"."bills" ("invoice_number");

CREATE INDEX "idx_payment_transactions_clinic_id" ON "public"."payment_transactions" ("clinic_id");
CREATE INDEX "idx_payment_transactions_razorpay_payment_id" ON "public"."payment_transactions" ("razorpay_payment_id");
CREATE INDEX "idx_payment_transactions_status" ON "public"."payment_transactions" ("payment_status");

CREATE INDEX "idx_medicines_name" ON "public"."medicines" ("name");
CREATE INDEX "idx_medicines_manufacturer" ON "public"."medicines" ("manufacturer_name");

CREATE INDEX "idx_prescriptions_clinic_id" ON "public"."prescriptions" ("clinic_id");
CREATE INDEX "idx_prescriptions_patient_id" ON "public"."prescriptions" ("patient_id");
CREATE INDEX "idx_prescriptions_doctor_id" ON "public"."prescriptions" ("doctor_id");
CREATE INDEX "idx_prescriptions_appointment_id" ON "public"."prescriptions" ("appointment_id");
CREATE INDEX "idx_prescriptions_consultation_id" ON "public"."prescriptions" ("consultation_id");

CREATE INDEX "idx_appointment_billing_clinic_id" ON "public"."appointment_billing" ("clinic_id");
CREATE INDEX "idx_appointment_billing_monthly_cycle_id" ON "public"."appointment_billing" ("monthly_billing_cycle_id");

CREATE INDEX "idx_monthly_billing_cycles_clinic_id" ON "public"."monthly_billing_cycles" ("clinic_id");
CREATE INDEX "idx_monthly_billing_cycles_billing_month" ON "public"."monthly_billing_cycles" ("billing_month");
CREATE INDEX "idx_monthly_billing_cycles_payment_status" ON "public"."monthly_billing_cycles" ("payment_status");